### ISSUE TITLE
crashhhh???

### ISSUE THREAD

**Issue by sujjeee** [Dhravya/dump.place#1]
![Screenshot 2023-12-25 230535](https://github.com/Dhravya/dump.place/assets/101963203/9a84b526-6623-4999-bb31-17d78a4e3e14)

**Comment by Dhravya** [comment]
Yes, all my websites were down because of an attack https://x.com/dhravyashah/status/1739360599518154875?s=46&t=y_rLgPvxfj4DKPUMA7ZOtw
