### ISSUE TITLE
Faster queries

### ISSUE THREAD

**Issue by Dhravya** [Dhravya/dump.place#11]
The database read/writes are very slow, 

Query speeds can be improved using
- a complete rewrite of the db to redis 
- more efficient queries

**Comment by anuragts** [comment]
Is migration to Redis a good decision, how's the performance now and can also add pagination(infinite or pages) in the home page to improve performance.

**Comment by Dhravya** [comment]
I think we only need to optimise the write operation, so a complete migration isn't worth it

**Comment by kenneropia** [comment]
Hello there @Dhravya and @anuragts , will a rewrite to redis be worth it, asking because will you be okay with the fact that the data will be ephemeral? not sure about your plans for the continuous usage of the app. Sorry for randomly joining the conversation, my name is aaron, I am looking for ways to contribute to the project soon, please be expecting my draft pr/proposal soon.
Cheers.

**Comment by Dhravya** [comment]
@kenneropia data in redis is not always ephemeral (see https://github.com/lmfao-tech, where all the posts were stored in redis!) a TTL of infinite can be set to redis databases

Really nice to see that you want to contribute! I have some issues open, for eg #16

**Comment by kenneropia** [comment]
Okay, thanks. I appreciate. I will signify as soon as I am ready.

**Comment by Dhravya** [comment]
actually, let's not rewrite it to redis, we need ways to make it feel faster now, that's it. 


- caching on the home page 
- showing the dump before it's published and then revalidating the path

stuff like that should do it I just added pgbouncer for the database and ever since then everything has been working slightly better

**Comment by kenneropia** [comment]
1. Regarding this, would you recommend using Redis, the newly built cache function that comes with React/Next, or a regular in-memory library? Also, what would be the recommended Time-to-Live (TTL) and the length of the dumps to be cached?

2. By this, are you referring to something like optimistic updates? I observed that you are using server actions; you can make use of the new userFormStatus or startTransition to monitor the form submission status and eliminate some queries in the server actions function.

Does this align with your thoughts and plans? What would you suggest?

**Comment by Dhravya** [comment]
Cache function with NextJS would work, don't want to overcomplicate things 

and yes, optimistic updates
