### ISSUE TITLE
Displaying post as request is send.

### ISSUE THREAD

**Issue by anuragts** [Dhravya/dump.place#12]
Displaying the post as the request is sent to the server can enhance performance. Subsequently, revalidating after the request is completed further refines the process.

**Comment by Dhravya** [comment]
@anuragts would you like to take on this issue?

**Comment by kenneropia** [comment]
Hello, can I take this, if they are not interested?

**Comment by Dhravya** [comment]
hi, yes, assigning. but pls only do it on the [username] page, as I'm working on some major changes to the app

**Comment by kenneropia** [comment]
I am on it.

**Comment by kenneropia** [comment]
How about this? does it make sense?

https://github.com/Dhravya/dump.place/assets/52609237/8f057d2e-195e-4719-99d7-e90f24af0a33

**Comment by kenneropia** [comment]
Please review https://github.com/Dhravya/dump.place/pull/38
