### ISSUE TITLE
Add toast bars 

### ISSUE THREAD

**Issue by Dhravya** [Dhravya/dump.place#17]
use https://sonner.emilkowal.ski/ to add toast notifications upon successful, fail, and other operations. The server actions already send responses for success/failure but it's not shown to the user

**Comment by yxshv** [comment]
> use https://sonner.emilkowal.ski/ to add toast notifications upon successful, fail, and other operations. The server actions already send responses for success/failure but it's not shown to the user

No need for a library, it's pretty easy to make

**Comment by yxshv** [comment]
Will try to replicate it today 👍

**Comment by Dhravya** [comment]
just use a library pls https://x.com/emilkowalski_/status/1740049351865729177?s=46&t=y_rLgPvxfj4DKPUMA7ZOtw

**Comment by Knightabhi** [comment]
Hi, Nice work I will love to contribute this
