### ISSUE TITLE
Loading states

### ISSUE THREAD

**Issue by Dhravya** [Dhravya/dump.place#19]
Add loading.tsx files and show a skeleton-like UI for loading

More info and docs here https://nextjs.org/docs/app/building-your-application/routing/loading-ui-and-streaming

**Comment by T1LT** [comment]
hey! would love to work on this!

**Comment by Dhravya** [comment]
@T1LT Assigned!

**Comment by T1LT** [comment]
thank you @Dhravya 
i wanted to discuss this a little bit before getting started though.

**Comment by Dhravya** [comment]
You can DM me on twitter!
