### ISSUE TITLE
Prevent certain character from being included in username or parse them properly

### ISSUE THREAD

**Issue by kenneropia** [Dhravya/dump.place#20]
Hello guys, I used "adetunmbikenny@gmail.com" as a username and because the username is on the URL on the profile page, characters like "@" and "<" are converted to %40 and %3E respectively, you can check for more info on this [here](https://www.w3schools.com/tags/ref_urlencode.ASP). 

We can either prevent those type of character from the form or convert the string(like adetunmbikenny%40gmail.com to "@adetunmbikenny@gmail.com") before passing the payload to the db.

Context:
![image](https://github.com/Dhravya/dump.place/assets/52609237/b0d8b8cb-5a03-463b-89c1-00b6321a7484)

Please, can I create a PR for this and work on it and please if so, kindly choose the approach to go with it. Thanks.

**Comment by Dhravya** [comment]
Yes, please go ahead, we only want English characters a-z A-Z -_ 0-9

**Comment by Dhravya** [comment]
(lowercase only)

**Comment by Dhravya** [comment]
fixed

**Comment by kenneropia** [comment]
I was already working on it on my local branch🥲, please don’t take the other one I have started working on it.

**Comment by Dhravya** [comment]
my bad, this was pretty urgent so I just got it done
